zeebe:
  client:
    worker:
      defaultName: nacos-worker
      defaultType: nacos_service
      threads: 3

    job.timeout: 120000
    security.plaintext: true
    broker:
      gateway-address: 10.0.1.198:26500

  nacos:
    service:
      name: SERVICE_NAME
      suffix: METHOD_NAME

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: zeebe-nacos-worker
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.1.198:8848
        register-enabled: true

server:
  port: 8080

nextop:
  zeebe:
    nacos:
      metadata:
        enabled: true