zeebe:
  client:
    worker:
      defaultName: nacos-worker
      defaultType: nacos_service
      threads: 3

    job.timeout: 120000
    security.plaintext: true
    broker:
      gateway-address: 10.0.1.198:26500

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.http: DEBUG

management:
  server:
    port: 8080

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.1.198:8848
        metadata:
          find: /order/find
          add: /order/create
          delete: /order/delete
          update: /order/update

